spring:
  application:
    name: zuul-gateway
server:
  port: 8088
zuul:
  routes:
    oauth-resource:
      path: /resource/**
      serviceId: resource-server
    oauth:
      path: /oauth/**
      serviceId: auth-server
    country:
      path: /country/**
      serviceId: countries
