spring:
  application:
    name: zuul-gateway
server:
  port: 8088
zuul:
  routes:
    oauth:
      path: /uaa/**
      serviceId: auth-server
      sensitiveHeaders:
    country:
      path: /country/**
      serviceId: countries
security:
  oauth2:
    client:
      origin: http://localhost:3000

